name: housing_payment
description: Flutter Housing Payment

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  shared_preferences: ^2.0.5
  flutter_svg:  ^0.20.0-nullsafety.3
  retrofit: any
  logger: any
  json_annotation: ^3.0.1
  fluttertoast: ^7.0.2
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  cached_network_image: ^2.4.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  json_serializable: ^3.4.0
  build_runner: any

dependency_overrides:
  analyzer: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
